package gqlMain;


//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jul 21 20:52:32 EDT 2012
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHERE = 17;
  public static final int RBRACK = 8;
  public static final int AND = 23;
  public static final int UNDERSCORE = 9;
  public static final int COMPARISON = 22;
  public static final int POSNUMBER = 26;
  public static final int RPAREN = 5;
  public static final int EQUAL = 11;
  public static final int SEMI = 2;
  public static final int IN = 15;
  public static final int STAR = 10;
  public static final int S = 27;
  public static final int NODES = 19;
  public static final int PATHS = 21;
  public static final int LBRACK = 7;
  public static final int RETURN = 16;
  public static final int ERROR = 12;
  public static final int VARIABLE = 18;
  public static final int LPAREN = 4;
  public static final int STRING = 25;
  public static final int COMMA = 3;
  public static final int NUMBER = 24;
  public static final int EOF = 0;
  public static final int EDGES = 20;
  public static final int error = 1;
  public static final int DOT = 6;
  public static final int LET = 13;
  public static final int FOR = 14;
}

